name: Deploy sur le VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy compose file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/opt/app"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          PORT: ${{ vars.PORT }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_USER: ${{ vars.DB_USER }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_PORT: ${{ vars.DB_PORT }}
          JWT_EXPIRES_IN: ${{ vars.JWT_EXPIRES_IN }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}

          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: NODE_ENV,PORT,DB_HOST,DB_USER,DB_NAME,DB_PORT,JWT_EXPIRES_IN,VITE_API_URL,DB_PASSWORD,DB_ROOT_PASSWORD,JWT_SECRET,DOCKERHUB_USERNAME,DOCKERHUB_TOKEN
          script: |
            set -e

            mkdir -p /opt/app
            cd /opt/app

            cat > .env <<EOF
            NODE_ENV=${NODE_ENV}
            PORT=${PORT}

            DB_HOST=${DB_HOST}
            DB_USER=${DB_USER}
            DB_PASSWORD=${DB_PASSWORD}
            DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            DB_NAME=${DB_NAME}
            DB_PORT=${DB_PORT}

            JWT_SECRET=${JWT_SECRET}
            JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

            VITE_API_URL=${VITE_API_URL}
            EOF

            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"

            docker compose -f docker-compose.prod.yml config
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f
